from __future__ import annotations

import argparse
import gzip
import hashlib
import shutil
import subprocess
import zipfile
from pathlib import Path


DEFAULT_QGIS_ROOT = Path(r"C:\Program Files\QGIS 3.40.12")
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "ThirdParty" / "PDAL" / "Windows"


def copy_tree(source: Path, destination: Path, dry_run: bool) -> int:
    if not source.exists():
        return 0
    copied = 0
    for item in source.rglob("*"):
        if not item.is_file():
            continue
        target = destination / item.relative_to(source)
        print(f"{item} -> {target}")
        copied += 1
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, target)
    return copied


def copy_file(source: Path, destination: Path, dry_run: bool) -> bool:
    if not source.exists() or not source.is_file():
        return False
    print(f"{source} -> {destination}")
    if not dry_run:
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    return True


def copy_osgeo_package_list(qgis_root: Path, output_root: Path, package_name: str, dry_run: bool) -> int:
    package_list = qgis_root / "etc" / "setup" / f"{package_name}.lst.gz"
    if not package_list.exists():
        return 0

    copied = 0
    with gzip.open(package_list, "rt", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            parts = line.split()
            if len(parts) < 6:
                continue
            relative_path = parts[-1]
            if relative_path.endswith("/"):
                continue
            source = qgis_root / relative_path
            target = output_root / relative_path
            copied += 1 if copy_file(source, target, dry_run) else 0
    return copied


def write_runtime_metadata(output_root: Path, qgis_root: Path, dry_run: bool) -> None:
    pdal_path = output_root / "bin" / "pdal.exe"
    version = "unknown"
    if pdal_path.exists():
        try:
            result = subprocess.run(
                [str(pdal_path), "--version"],
                cwd=str(pdal_path.parent),
                check=True,
                capture_output=True,
                text=True,
            )
            version = (result.stdout or result.stderr).strip()
        except Exception as exc:
            version = f"unknown ({exc})"

    manifest = output_root / "BUNDLE_MANIFEST.txt"
    content = (
        "CSTopo bundled PDAL runtime\n"
        f"Source root: {qgis_root}\n"
        f"PDAL version: {version}\n"
        "Generated by: scripts/vendor_pdal_runtime.py\n"
        "\n"
        "This folder is staged into packaged CSTopo builds. Keep third-party notices with the runtime.\n"
    )
    print(f"write {manifest}")
    if not dry_run:
        manifest.parent.mkdir(parents=True, exist_ok=True)
        manifest.write_text(content, encoding="utf-8")


def vendor_runtime(qgis_root: Path, output_root: Path, dry_run: bool) -> None:
    if not qgis_root.exists():
        raise SystemExit(f"QGIS root was not found: {qgis_root}")

    package_names = [
        "pdal",
        "pdal-libs",
        "gdal311-runtime",
        "proj9-runtime",
        "proj-runtime-data",
    ]

    copied = 0
    copied += copy_tree(qgis_root / "bin", output_root / "bin", dry_run)

    for package_name in package_names:
        copied += copy_osgeo_package_list(qgis_root, output_root, package_name, dry_run)

    copied += copy_tree(qgis_root / "apps" / "pdal" / "plugins", output_root / "apps" / "pdal" / "plugins", dry_run)
    copied += copy_tree(qgis_root / "apps" / "gdal" / "share" / "gdal", output_root / "apps" / "gdal" / "share" / "gdal", dry_run)

    for name in ("LICENSE.TXT", "README.TXT", "VERSION.txt"):
        copy_file(qgis_root / "apps" / "gdal" / "share" / "gdal" / name, output_root / "licenses" / f"gdal-{name}", dry_run)

    write_runtime_metadata(output_root, qgis_root, dry_run)
    print(f"{'Would copy' if dry_run else 'Copied'} {copied} runtime file(s).")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def package_runtime(runtime_root: Path, zip_path: Path) -> str:
    pdal_path = runtime_root / "bin" / "pdal.exe"
    if not pdal_path.exists():
        raise SystemExit(f"PDAL executable was not found in prepared runtime: {pdal_path}")

    zip_path.parent.mkdir(parents=True, exist_ok=True)
    zip_path_resolved = zip_path.resolve()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for item in sorted(runtime_root.rglob("*")):
            if not item.is_file():
                continue
            if item.resolve() == zip_path_resolved:
                continue
            archive.write(item, item.relative_to(runtime_root).as_posix())

    checksum = sha256_file(zip_path)
    print(f"Packaged runtime ZIP: {zip_path}")
    print(f"SHA-256: {checksum}")
    print("Manifest checksum field:")
    print(f'  "sha256": "{checksum}"')
    return checksum


def main() -> None:
    parser = argparse.ArgumentParser(description="Populate CSTopo's bundled Windows PDAL runtime from a local QGIS/OSGeo4W install.")
    parser.add_argument("--qgis-root", type=Path, default=DEFAULT_QGIS_ROOT, help="source QGIS/OSGeo4W installation root")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT, help="output ThirdParty/PDAL/Windows runtime folder")
    parser.add_argument("--dry-run", action="store_true", help="show files without copying")
    parser.add_argument("--package-zip", type=Path, help="zip the prepared runtime folder and print its manifest SHA-256")
    parser.add_argument("--package-only", action="store_true", help="skip copying from QGIS and package the existing output folder")
    args = parser.parse_args()

    if not args.package_only:
        vendor_runtime(args.qgis_root, args.out, args.dry_run)

    if args.package_zip:
        if args.dry_run:
            raise SystemExit("--package-zip cannot be combined with --dry-run")
        package_runtime(args.out, args.package_zip)


if __name__ == "__main__":
    main()
